export const UPDATE_USER = "UPDATE_USER";
export const GET_IMAGES_PER_CATEGORY = "GET_IMAGES_PER_CATEGORY";
export const GET_IMAGE_BY_ID = "GET_IMAGE_BY_ID";
export const POPULATE_IMAGES = "POPULATE_IMAGES";
export const SELECT_CATEGORY = "SELECT_CATEGORY";